[tool.poetry]
name = "z3"
version = "0.1.0"
description = ""
authors = ["lhleung <grandq33769@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
z3-solver = "^4.8.17"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
